### ISSUE TITLE
Misc Todo

### ISSUE THREAD

**Issue by DatDraggy** [DatDraggy/summerbo.at#28]
- [x] Add ability to swap boats form userarea
- [x] ~~Transfer Script~~ **Moved**
- [x] Waitinglist
- [x] Test waitinglist
- [x] ~~Shuttle Bus Option in Userarea~~ **Moved**
